# Copyright 2021 dwellir
# See LICENSE file for licensing details.
#
options:
  binary-url:
    type: string
    default: ""
    description: |
      Path to download one or multiple binaries or a single .deb file.

      Example 1: https://github.com/paritytech/polkadot-sdk/releases/download/polkadot-v1.1.0/polkadot-parachain

      Example 2: "https://github.com/paritytech/polkadot-sdk/releases/download/polkadot-v1.1.0/polkadot https://github.com/paritytech/polkadot-sdk/releases/download/polkadot-v1.1.0/polkadot-execute-worker https://github.com/paritytech/polkadot-sdk/releases/download/polkadot-v1.1.0/polkadot-prepare-worker"

      Example 3: https://github.com/ComposableFi/composable/releases/download/release-v9.10035.5/composable-node_8.10035.5-1_amd64.deb

      Different installation methods will be used depending on if a .deb file is used or not.

      Note: multiple binary install is currently only supported for Polkadot relay chains, parachain support is not confirmed.
  binary-sha256-url:
    type: string
    default: ""
    description: |
      If the URL is provided, the charm downloads the sha256 and performs a checksum check against the binary.

      Note 1: needs to point to the sha256 corresponding to the 'binary-url' ahead of downloading the binary to actually perform the check!

      Note 2: if multiple binary URL:s are supplied, multiple sha256 URL:s should be supplied as well, in the same order.

      Note 3: it's also possible to provide one sha256 URL with multiple binary URL:s if the sha256 file contains one row per binary.
  docker-tag:
    type: string
    default: ""
    description: "The tag of the docker image to extract binary from. E.g. v1.5.0"
  service-args:
    type: string
    default: ""
    description: |
      Extra arguments that the service should run with.

      '--chain=... --rpc-port=...' are required to set for the charm to run.
  validator-address:
    type: string
    default: ""
    description: |
      If this is set, update-status will check if this node is currently validating for this address.
      HINT: if this config parameter is set, the actions is-validating-this-era and is-validating-next-era can be used.
  parachain-spec-url:
    type: string
    default: ""
    description: |
      If this is set, the chain spec will be downloaded from this URL and used as the value for the --chain argument of the Polkadot binary.
