{
 "title": "Polkadot-Dotsama Ecosystem Dashboard",
 "description": "A dashboard for monitoring substrate node metrics.\n\nBased on \"My Polkadot Metrics\" by phillux\nhttps://grafana.com/grafana/dashboards/12425",
 "tags": [
  "RPC",
  "POLKADOT"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "lokids", "label": "Loki datasource", "query": "loki" },
   { "name": "prometheusds", "label": "Prometheus datasource", "query": "prometheus" },
   {
    "name": "juju_unit",
    "label": "Juju unit",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_application=~\"$juju_application\"},juju_unit)"
    }
   },
   {
    "name": "juju_application",
    "label": "Juju application",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\"},juju_application)"
    }
   },
   {
    "name": "juju_model_uuid",
    "label": "Juju model uuid",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\"},juju_model_uuid)"
    }
   },
   { "name": "juju_model", "label": "Juju model", "query": { "query": "label_values(up,juju_model)" } },
   {
    "name": "Prefix",
    "label": "Metric Prefix",
    "query": "substrate, darwinia_substrate, moonbeam_substrate"
   }
  ]
 },
 "panels": [
  {
   "title": "Finalized blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "${Prefix}_block_height{status=\"best\",juju_model=\"${juju_model}\",juju_application=~\"$juju_application\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC requests (millions) / per hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(${Prefix}_rpc_requests_started{juju_model=\"${juju_model}\"}[1h]))/1000000",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "RPC sessions started per hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(${Prefix}_rpc_sessions_opened{juju_model=\"${juju_model}\"}[1h])",
     "legendFormat": "Sessions started"
    }
   ]
  },
  { "title": "RPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "RPC sessions started per day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "increase(${Prefix}_rpc_sessions_opened{juju_model=\"${juju_model}\"}[1d])",
     "legendFormat": "Sessions started"
    }
   ]
  },
  {
   "title": "RPC requests (millions) / per day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(${Prefix}_rpc_requests_started{juju_model=\"${juju_model}\"}[1d]))/1000000",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Websocket Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(${Prefix}_rpc_requests_started{juju_model=\"${juju_model}\",protocol=\"ws\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(${Prefix}_rpc_requests_started{juju_model=\"${juju_model}\",protocol=\"http\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Live Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "${Prefix}_rpc_sessions_opened{juju_model=\"${juju_model}\"} - ${Prefix}_rpc_sessions_closed{juju_model=\"${juju_model}\"}",
     "legendFormat": "request started"
    }
   ]
  },
  {
   "title": "Data egress (KB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{juju_model=\"${juju_model}\"}[$__rate_interval])/1000",
     "legendFormat": "request started"
    }
   ]
  },
  {
   "title": "RPC call time 95th Pecentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(${Prefix}_rpc_calls_time_bucket{juju_model=\"${juju_model}\"}[5m])) by (le))",
     "legendFormat": "rpc call processing duration for 95% of requests."
    }
   ]
  },
  {
   "title": "RPC requests per day at any given moment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "rate(${Prefix}_rpc_requests_started{juju_model=\"${juju_model}\"}[1h])*86400"
    }
   ]
  },
  {
   "title": "Request Started by type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(${Prefix}_rpc_calls_started{juju_model=\"${juju_model}\"}[5m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Cumulative RPC Sessions Closed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "${Prefix}_rpc_sessions_closed{juju_model=\"${juju_model}\"}",
     "legendFormat": "request started"
    }
   ]
  },
  {
   "title": "Requests last 24 h",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(${Prefix}_rpc_requests_started{juju_model=\"${juju_model}\"}[24h])",
     "legendFormat": "increase in request in last 24 hours"
    }
   ]
  },
  {
   "title": "Block height",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "${Prefix}_block_height{juju_model=\"${juju_model}\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Core", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Block verification and import time",
   "type": "timeseries",
   "description": "95th Percentile",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(${Prefix}_block_verification_and_import_time_bucket{juju_model=\"${juju_model}\"}[5m])) by (le))",
     "legendFormat": "Block verification and import duration for 95% of requests."
    }
   ]
  },
  {
   "title": "System Restarts in last 24h",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "resets(${Prefix}_rpc_requests_started{juju_model=\"${juju_model}\"}[24h])",
     "legendFormat": "system restarts"
    }
   ]
  },
  {
   "title": "Peers connected, discovered, and requested",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "${Prefix}_sub_libp2p_peers_count{juju_model=\"${juju_model}\"}",
     "legendFormat": "Peers count"
    },
    {
     "expr": "${Prefix}_sub_libp2p_peerset_num_discovered{juju_model=\"${juju_model}\"}",
     "legendFormat": "Discovered peers"
    },
    {
     "expr": "${Prefix}_sub_libp2p_peerset_num_requested{juju_model=\"${juju_model}\"}",
     "legendFormat": "Requested peers"
    }
   ]
  },
  {
   "title": "Connected peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "${Prefix}_sync_peers{juju_model=\"${juju_model}\"}"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "Tasks rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(${Prefix}_tasks_polling_duration_bucket{juju_model=\"${juju_model}\"}[5m])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Running Tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(${Prefix}_tasks_polling_started_total{juju_model=\"${juju_model}\"}[1m]) - rate(${Prefix}_tasks_polling_duration_count{juju_model=\"${juju_model}\"}[1m])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "State Cache DB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "${Prefix}_state_db_cache_bytes{juju_model=\"${juju_model}\"}",
     "legendFormat": "{{subtype}}"
    }
   ]
  },
  {
   "title": "Queued Blocks (sync)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "${Prefix}_sync_queued_blocks{juju_model=\"${juju_model}\"}"
    }
   ]
  },
  {
   "title": "State Cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "${Prefix}_state_cache_bytes{juju_model=\"${juju_model}\"}"
    }
   ]
  },
  {
   "title": "Number of Leaves",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "${Prefix}_number_leaves{juju_model=\"${juju_model}\"}"
    }
   ]
  },
  {
   "title": "Number of transactions in the ready queue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "${Prefix}_ready_transactions_number{juju_model=\"${juju_model}\"}",
     "legendFormat": "Number of transactions in the ready queue"
    }
   ]
  }
 ]
}