name: Charm Tests

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  charm-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up uv
        uses: astral-sh/setup-uv@v6

      - name: Run charm tests
        run: make charm-test
